---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    base_image: debian:buster
    container_name: solr_build_container
    image_namespace: geerlingguy
    image_name: solr

  pre_tasks:
    - name: Extract the major version from solr_version
      set_fact:
        solr_major_version: "{{ solr_version.split('.')[0] }}"

    - name: Make the latest version of the base image available locally.
      docker_image:
        name: '{{ base_image }}'
        source: pull
        force_source: true

    - name: Create the Docker container.
      docker_container:
        image: '{{ base_image }}'
        name: '{{ container_name }}'
        command: sleep infinity
        env_file: 'files/{{ solr_major_version }}.x.env'

    - name: Add the newly created container to the inventory.
      add_host:
        hostname: '{{ container_name }}'
        ansible_connection: docker
        ansible_python_interpreter: /usr/bin/python3

    - name: Ensure Python is installed.
      raw: >
        apt-get update &&
        apt-get install -y --no-install-recommends python3
      changed_when: true
      delegate_to: '{{ container_name }}'

    - name: Gather facts inside the container.
      setup:
      delegate_to: '{{ container_name }}'

  roles:
    - name: setup
      delegate_to: '{{ container_name }}'

    - name: geerlingguy.java
      delegate_to: '{{ container_name }}'

    - name: geerlingguy.solr
      delegate_to: '{{ container_name }}'

  post_tasks:
    - name: Clean up the container.
      shell: |
        apt-get remove --purge -y python3
        rm -rf /var/lib/apt/lists/*
      changed_when: true
      delegate_to: '{{ container_name }}'

    - name: Commit the container.
      command: >
        docker commit
        -c 'CMD {{ container_start_command }}'
        -c 'WORKDIR {{ container_working_dir }}'
        {{ container_name }} {{ image_namespace }}/{{ image_name }}:{{ solr_version }}
      changed_when: true

    - name: Remove the container.
      docker_container:
        name: '{{ container_name }}'
        state: absent
